server:
  port: 10102

logging:
  level:
    com.adtech: debug

spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://192.168.199.15:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      minimum-idle: 8
      maximum-pool-size: 300
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: DataPookHikariCP
      test-while-idle: true
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000